# Generated by Django 4.2 on 2023-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('genres', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
