# Generated by Django 4.2 on 2023-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteSuggest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imagePoster',
            field=models.ImageField(default='images/nonPoster.png', upload_to='images'),
        ),
    ]
