# Generated by Django 4.2 on 2023-05-21 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websiteSuggest', '0002_movies_imageposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movieId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='watchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSuggest.movies')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchLater',
            },
        ),
    ]
